spring:
  application:
    name: rag

  datasource:
    url: jdbc:postgresql://**********.c-4.us-east-1.aws.neon.tech/recommendation-agent?sslmode=require&channel_binding=require
    username: user
    password: ABCD
    driver-class-name: org.postgresql.Driver

  ai:
    google:
      genai:
        api-key: XXXXXXXXXXXXXXXX
        chat:
          options:
            model: gemini-2.5-flash-lite
        embedding:
          api-key: XXXXXXXXXXXXXXXX
          text:
            options:
              model: gemini-embedding-001
              dimensions: 1536
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
